### ISSUE TITLE
Instead of determine all properties and then exclude properties why not choose selective running (native git)

### ISSUE THREAD

**Issue by TheSnoozer** [git-commit-id/maven-git-commit-id-plugin#185]
Hi,
currently the plugin has the option to exclude some properties or not. This is really usefull and I use this on a daily basis (yeah customers don't want to have some properties in some sensitive files).
However, for the native git the plugin currently determines all properties with calls to the git executable.
Each call coast a few milli seconds build time. So what the native git implementation currently does it will call the git executable, determine the result and when this is done the properties get's filtered out if they should be excluded.
Why not just skip the call to the binary, when the property isn't wanted anyway?
For each property this would speed up the runtime for the native git implementation.

As far as I know changing the behavoir for the jgit-implementation wouldn't speed up the build process. This is due to the fact that the jgit implementation just gathers all information that it could get and the maven-git-commit-id-plugin just asks for them afterwards (as far as I know there is no second call to the jgit-implementation).

Just to get the Idea why I'm suggesting this:
I'm using the native git and some similar config to this:

```
<excludeProperties>
                        <excludeProperty>git.branch</excludeProperty>
                        <excludeProperty>git.build.*</excludeProperty>
                        <excludeProperty>git.commit.user.*</excludeProperty>
                        <excludeProperty>git.commit.message.*</excludeProperty>
                        <excludeProperty>git.commit.time</excludeProperty>
                        <excludeProperty>git.commit.id.describe-short</excludeProperty>
                        <excludeProperty>git.remote.origin.url</excludeProperty>
</excludeProperties>
```

this means exclude everything and just keep git.commit.id and git.commit.id.abbrev....
so in my case I would speed up the build process by probability 1s :D

**Comment by goranmagdic** [comment]
Hi, 

I find plugin very slow in my case and I only need commit.id information, so I assume it would be much faster if it did not parse the whole tag history. is there maybe something already that I am missing?

**Comment by TheSnoozer** [comment]
Can you elaborate further on what "slow" means for you?
Can you paste your full configuration here?
Are you doing a shallow clone or full clone of the git repository?
Have you tried the native git implementation?

**Comment by goranmagdic** [comment]
Just counting while maven is stuck on plugin I got to 9 sec. That is for one module. 
I can paste plugin configuration, not the whole project: 
`<plugin>
			<groupId>pl.project13.maven</groupId>
			<artifactId>git-commit-id-plugin</artifactId>
			<version>2.2.1</version>
			<executions>
				<execution>
					<id>get-the-git-infos</id>
					<goals>
						<goal>revision</goal>
					</goals>
				</execution>
			</executions>
			</plugin>`
I assume full clone since I did not specify depth. 
Using native git improves it a bit; 3 sec faster.

**Comment by TheSnoozer** [comment]
just for clarification:
by referring to 9 seconds it takes only the git plugin a total of 9 seconds to determine the all the properties, or is this referring to the whole build cycle? How are you measuring the 9 VS 6 seconds?
Are you using a profiler like https://github.com/takari/maven-profiler or https://github.com/jcgay/maven-profiler?

How many commit are in your repository? (`git rev-list --all --count`)

I don't need the full config I just needed the info of the plugin itself - so all good :-)

**Comment by goranmagdic** [comment]
9 seconds is  just for a plugin, (so the full build is ~19 vs ~16 sec)
I did not use profiler, I just counted seconds myself. Looking at maven output at one point it stops on 

```[INFO]
[INFO] --- git-commit-id-plugin:2.2.1:revision (get-the-git-infos) @ <my project>---
[INFO]
```
And then I just count 1, 2, 3, in my head :), it is not very reliable method, but gives you approximate value (or order of magnitude).
Number of commits might be a problem:
$ git rev-list --all --count
139011
The problem is I just need commit id, maybe I should be using some other plugin or approach for that?

**Comment by Nogyara** [comment]
If I got it right, this issue if about skipping of evaluation of excluded git properties when they won't be used anyway. One more reason to support this:

On our CI, Atlassian Bamboo, we use Git feature[ Use shallow clone](https://confluence.atlassian.com/bamboo/git-289277007.html), which only retrieves the last commit from Git repo as opposed to cloning the whole history. However, this causes this Maven plugin to fail, as it tries to walk the history back to the closest tag (git.closest.* properties) - but there's no history to be walked.

As this is a quite useful Git feature (not limited to Atlassian Bamboo) which saves build time on CI, and on the other hand, git.closest.* properties usefulness depends on use case (for instance, we don't need it), I'd really great to see this issue fixed, dropping shallow cloning feature and slow down our CI builds is not a compelling option.

**Comment by Nogyara** [comment]
I just notice what I described here is actually already described in #61

**Comment by TheSnoozer** [comment]
Hi thanks for your comment and I agree that it would be very useful to have this feature available.
In general the plugin is gathering all properties and then applies filtering. As you mentioned the idea is really not to try to get properties that are excluded in the filtering anyways.

Two main benefits:
1) plugin would run way faster if a build is only interested in the commit hash
2) plugin would only "break" if something that is desired is really missing

As of now this is scheduled for the next release, but I haven't gotten the time to work on it (mainly to the fact that I no longer work with maven :P)

In terms for your issue to to add ``<useNativeGit>true</useNativeGit>`` to the configuration of the plugin. 

I also opened https://github.com/ktoso/maven-git-commit-id-plugin/issues/373 to investigate this further.

**Comment by TheSnoozer** [comment]
Fixed with https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/414
