### ISSUE TITLE
Bamboo build number do not use the right case

### ISSUE THREAD

**Issue by nicolasmingo** [git-commit-id/maven-git-commit-id-plugin#410]
### Describe the bug
When I use git-commit-id plugin in my maven project I want to have git.build.number inside git.properties, but it does not work on Bamboo.

### Steps to Reproduce

```xml
<plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.6</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>

                </executions>
                <configuration>
                    <generateGitPropertiesFile>
                        true
                    </generateGitPropertiesFile>
                    <generateGitPropertiesFilename>
                        ${project.build.outputDirectory}/git.properties
                    </generateGitPropertiesFilename>
                </configuration>
</plugin>
```
### Actual behavior
git.build.number is missing

### Expected behavior
git.build.number=``number``

### Additional context
I've reproduced the bug in my IDE by injecting ENV variables like in bamboo.

If i put env-vars like bamboo (with the exact case) 
bamboo_buildKey=MY_KEY
bamboo_buildNumber=18
Then it does not work

If i put env-vars like bamboo (but in uppercase) 
BAMBOO_BUILDKEY=MY_KEY
BAMBOO_BUILDNUMBER=18
Then it works

**Comment by TheSnoozer** [comment]
Ahh thanks for reporting your issue.
This seems to be a "use the right casing" issue.

In the relevant part that tries to extract the bamboo-information (see [here](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/a276551fb043d1b7fc4c890603f6ea0c79dc729a/src/main/java/pl/project13/maven/git/build/BambooBuildServerData.java#L34)) we indeed try to extract `BAMBOO_BUILDKEY`, `BAMBOO_BUILDNUMBER` and `BAMBOO_PLANREPOSITORY_BRANCH`.

As per you comment, and the [Bamboo variables documentation](https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html#Bamboovariables-Build-specificvariables) this really should be `bamboo.buildKey`, `bamboo.buildNumber` and `bamboo.planRepository.<position>.branchName`. I'm wondering if `<position>` needs to be specified. Do you happen to know? Based on some comments `bamboo.planRepository.branchName` (https://stackoverflow.com/a/29249000) seems to work - but I'm not sure and have no way of testing/verify that.

**Comment by nicolasmingo** [comment]
bamboo.buildKey is replaced by bamboo_buildKey for env vars. (verified and tested).
For ``bamboo.planRepository.<position>.branchName``, I didn't have the issue.
