### ISSUE TITLE
Can't get a new or custom git.properties in Eclipse

### ISSUE THREAD

**Issue by dougbreaux** [git-commit-id/maven-git-commit-id-plugin#412]
### Describe the bug
I've been trying out different versions of making my `git.properties` have only the properties I want, but even with a `mvn clean install` from inside Eclipse, the generated file has every default property. Further, its "Generated by..." comment timestamp, `git.build.time` property, and file modification date all remain the same timestamp as when I first ran the build.

I'd say it's the same as (or similar to) #260, but a `mvn clean` isn't forcing.

### Steps to Reproduce
- Please include the **full** configuration of the plugin

Current setup is this, but I've also tried with `<includeProperties>` and only a few included.

```xml
<plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.6</version>

                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <excludeProperties>
                        <excludeProperty>git.*.user.*</excludeProperty>
                    </excludeProperties>
                </configuration>

</plugin>
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link.
- Include any stack-traces or any error messages

### Expected behavior
- Expect my includes or excludes to change both the timestamp and the contents of `git.properties`.

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk): **java.fullversion=8.0.5.25 - pwa6480sr5fp25-20181030_01(SR5 FP25)
JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20181029_400846 (JIT enabled, AOT enabled)
OpenJ9   - c5c78da
OMR      - 3d5ac33
IBM      - 8c1bdc2**
- the Maven-Version is being used (output of ``mvn --version``) **Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)**
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``) **Windows 10**
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...) **Eclipse.org - m2e Version 1.8.3.20180227-2137 in IBM Rational Application Developer 9.6.1.2**
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your problem here.
Mhh just curious who currently writes the `git.properties` file? If I remember correctly the configuration you provided should not make the plugin write a `git.properties` file....maybe it's just missing in your example?

For reference I have a project where i tried to troubleshoot this (see https://github.com/TheSnoozer/git-commit-id-debugging/blob/19204a86246dea3a265b6c75f7cfb25b033e24a9/submodule-one/pom.xml#L29) and it seems to work fine running from command-line. Is this only a problem when running maven within eclipse? Or is this also a problem when running maven via command-line? if it is only a problem with eclipse I would not be surprised if it might be related to https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/385

Could you perhaps try if this is still a problem with the latest 3.X-Snapshots (https://oss.sonatype.org/content/repositories/snapshots/pl/project13/maven/git-commit-id-plugin/3.0.0-SNAPSHOT/) ?


Also could you elaborate what you understand as a `default property` (`the generated file has every default property.`)? How does this look like?

**Comment by dougbreaux** [comment]
I hadn't tried outside Eclipse, but have done so now, and experience the same behavior. I do think I originally had `<generateGitPropertiesFile>true</generateGitPropertiesFile>`, if that's what seems to be missing. (I wasn't clear what the defaults were, was trying to go bare minimum.)

However, doing some digging, the behavior appears to be tied to my also using the `maven-assembly-plugin` `jar-with-dependencies`. It looks like the temp jar created has the updated properties, only the final one has the old/original `git.properties`. Still can't explain where the old copy could be coming from, though.

**Comment by dougbreaux** [comment]
Ok, it's the other project being pulled in with the `jar-with-dependencies` that is "hiding" these `git.properties` changes. Oddly, that project wasn't set up at all with this plugin, but apparently by virtue of pulling it in with maven-assembly-plugin, it generated a `git.properties` of its own, and that one is taking precedence over this one. 

However, when I modify the other project to also generate a `git.properties`, that doesn't cause it to generate a new file from building this _including_ project, only when I go build the _included_ project directly/separately.

Frankly, I don't know what the behavior should be with these two plugins together, so I'm ok with closing this Issue if you believe things are working-as-designed.

**Comment by dougbreaux** [comment]
Maybe `<runOnlyOnce>` is what I want here...

**Comment by TheSnoozer** [comment]
I'm sorry but I can't reproduce your issue.

I have added the maven-assembly-plugin to my sample project (https://github.com/TheSnoozer/git-commit-id-debugging/blob/master/submodule-one/pom.xml#L59) and everything seems to be working fine.

Do you have perhaps a `git.properties` inside your sources that gets copied over, but will not get filtered correctly?

The plugins should work together without any issues....at least I'm not aware of anything specific that is broken. If you could provide a reproducer with the issue I potentially could provide more feedback on what is going on.

I'm not sure how `runOnlyOnce` is somewhat related to your initial issue, so I'm somewhat lost....

**Comment by dougbreaux** [comment]
The issue seems to be that once I merged the contents of one repo with another into a single jar, even though I only had this plugin defined in the "master" ("including") one, both were generating a `git.properties`, and the "included" one was overwriting the "including" one. `<runOnlyOnce>` caused, in this case, only the "including" one to generate a `git.properties`, thus it was the one I wanted. 

So it could well be that this is working as designed and can be closed.
