### ISSUE TITLE
Cannot login to the server

### ISSUE THREAD

**Issue by zenochen** [git-commit-id/maven-git-commit-id-plugin#421]
the error is below:

org.eclipse.jgit.api.errors.TransportException: http://zeno@xxx.magiawall.org/r/ihoree/parent.git: Authentication is required but no CredentialsProvider has been registered

**Comment by TheSnoozer** [comment]
- What plugin version are you running?
- What maven command did you executed?
- Can you share your plugin config?
- Does this problem get fixed when you add the following exclusion rule to the config of the plugin?
```
<excludeProperties>
  <excludeProperty>^git.local.branch.*$</excludeProperty>
</excludeProperties>
```
- Can you run a normal `git pull` or `git fetch` in the directory and server where the build is happening?

**Comment by Sinth0r45** [comment]
Hello together. I am experiencing the same issue. It is only in version 3.0.0.

It appears with the command mvn git-commit-id:revision with the following config:

`<plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>${git-commit-id-plugin.version}</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                </configuration>
            </plugin>`

Adding the above mentioned tag to the configuration-tag makes the NullPointerException disappear.

**Comment by TheSnoozer** [comment]
Can you perhaps post the NullPointerException?
If the above fixes it it would justify the 'offline' mode setting (https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/424).

**Comment by Sinth0r45** [comment]
<img width="1369" alt="Stacktrace_" src="https://user-images.githubusercontent.com/53898079/62700239-b65f7480-b9e1-11e9-98ef-2c1d78b2f9a4.png">

**Comment by TheSnoozer** [comment]
Mhh...i know what the issue is and I'm not sure how to fix it.

With 3.0.0 we got two new properties (`git.local.branch.ahead` / `git.local.branch.behind`) that pretty much are only correct when using a `git pull` prior. This git pull might cause such transport exceptions (and requires internet).

With the 3.0.1 there will be a more clear `offline` option. The real fix would be that we have the plugin work in `offline` mode unless specified. When a user operates in `offline` mode and consumes the mentioned options this plugin would generate a warning.
Downside would be that the user's who already rely on the new properties would suddenly need to change their config.....but forcing existing users to change their config is not in any way better..

Opinions?

**Comment by TheSnoozer** [comment]
Please use the new `offline` mode that was introduced with 3.0.1 or the outlined [workaround](https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/421#issuecomment-507265145).

**Comment by Sinth0r45** [comment]
Alright then. Thank u for your support!

**Comment by logicatmidod** [comment]
How to set offline mode can you please provide document for that?

**Comment by joerg-vandervlies** [comment]
> How to set offline mode can you please provide document for that?

I found this commit that adds a brief paragraph regarding the documentation:
https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/424/commits/a34d1e5d537b4f4695d509fde17c5ba274a73444

With help of that commit I could add the following `<configuration>` to my plugin:
```
	<build>
		<plugins>
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<configuration>
					<offline>true</offline>
				</configuration>
			</plugin>
		</plugins>
	</build>

```

...and that's basically it.

cheers
Jörg

**Comment by Rickiyii** [comment]
> > How to set offline mode can you please provide document for that?
> 
> I found this commit that adds a brief paragraph regarding the documentation: [a34d1e5](https://github.com/git-commit-id/git-commit-id-maven-plugin/commit/a34d1e5d537b4f4695d509fde17c5ba274a73444)
> 
> With help of that commit I could add the following `<configuration>` to my plugin:
> 
> ```
> 	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>pl.project13.maven</groupId>
> 				<artifactId>git-commit-id-plugin</artifactId>
> 				<configuration>
> 					<offline>true</offline>
> 				</configuration>
> 			</plugin>
> 		</plugins>
> 	</build>
> ```
> 
> ...and that's basically it.
> 
> cheers Jörg

you are the boss
