### ISSUE TITLE
git-commit-id-plugin stops if remote repository is unavailable

### ISSUE THREAD

**Issue by kostousov-ds** [git-commit-id/maven-git-commit-id-plugin#426]
### Describe the bug
I have a project with remote repo in a private net. The plugin stops if it runs without connection to the private net.

### Steps to Reproduce
- Please include the **full** configuration of the plugin

```xml
<plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <version>3.0.0</version>
                    <executions>
                        <execution>
                            <phase>initialize</phase>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                        </execution>
                    </executions>
                            
                    <configuration>
                        <!-- that's the default value, you don't have to set it -->
                        <prefix>git</prefix>
                            
                        <!-- that's the default value -->
                        <dateFormat>dd.MM.yyyy '@' HH:mm:ss z</dateFormat>
                            
                        <!-- false is default here, it prints some more information during the build -->
                        <!--<verbose>true</verbose>-->
                        <!-- this is false by default, forces the plugin to generate the git.properties file -
->
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
            
                        <!-- The path for the to be generated properties file, it's relative to ${project.base
dir} -->
                        <generateGitPropertiesFilename>${git.properties}</generateGitPropertiesFilename>
                        <abbrevLength>12</abbrevLength>
                    </configuration>
</plugin>
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link.
- Include any stack-traces or any error messages

The last log from `mvn -X compile` output:
```
[DEBUG]   (f) runOnlyOnce = false
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@58fd1214
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipPoms = true
[DEBUG]   (f) skipViaCommandLine = false
[DEBUG]   (f) useBranchNameFromBuildEnvironment = true
[DEBUG]   (f) useNativeGit = false
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
[DEBUG] readpipe [git, --version],/usr/bin
[DEBUG] readpipe may return 'git version 2.21.0'
[DEBUG] remaining output:

[DEBUG] readpipe [git, config, --system, --edit],/usr/bin
[DEBUG] readpipe may return '/etc/gitconfig'
[DEBUG] remaining output:
```

The plugin proceeds after long time. All works fine after I connect to the private network. 

### Expected behavior
- Please provide a description of what you expected to happen.

The plugin should work if remote repo is unavailable, but Internet is connected.

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration)
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
- the Maven-Version is being used (output of ``mvn --version``)
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting your problem.
Based on the description it seems to be related to https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/424

Could you try if adding 
```xml
<excludeProperties><excludeProperty>^git.local.branch.*$</excludeProperty></excludeProperties>
``` 
to the configuration of the plugin fixes the "issue"? 

(I'm aware it will not fix the issue, but certainly should bypass it)

**Comment by TheSnoozer** [comment]
Please use the new `offline` mode that was introduced with 3.0.1 or the outlined [workaround](https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/426#issuecomment-514754973).
