### ISSUE TITLE
Property git.commit.user.email reports user name and not the email.

### ISSUE THREAD

**Issue by leerho** [git-commit-id/maven-git-commit-id-plugin#427]
### Describe the bug
Please provide a brief summary of the issue and provide a summarized description in the title above.

git property  git.commit.user.email reports user name and not the email.

### Steps to Reproduce
- Please include the **full** configuration of the plugin

```xml
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>${git-commit-id-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <dateFormatTimeZone>UTC</dateFormatTimeZone>
                    <verbose>false</verbose>
                    <skipPoms>false</skipPoms>
                    <format>json</format>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.directory}/git.properties</generateGitPropertiesFilename>
                    <failOnNoGitDirectory>true</failOnNoGitDirectory>
                    <failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>
                    <commitIdGenerationMode>full</commitIdGenerationMode>
                    <includeOnlyProperties>
                        <includeProperty>git.branch</includeProperty>
                        <includeProperty>git.build.version</includeProperty>
                        <includeProperty>git.closest.tag.name</includeProperty>
                        <includeProperty>git.commit.id.describe</includeProperty>
                        <includeProperty>git.commit.id.full</includeProperty>
                        <includeProperty>git.commit.message.full</includeProperty>
                        <includeProperty>git.commit.time</includeProperty>
                        <includeProperty>git.commit.user.email</includeProperty>
                        <includeProperty>git.tags</includeProperty>
                    </includeOnlyProperties>
                    <gitDescribe>
                        <skip>false</skip>
                        <always>true</always>
                        <abbrev>7</abbrev>
                        <dirty>-dirty</dirty>
                        <tags>true</tags>
                        <forceLongFormat>true</forceLongFormat>
                    </gitDescribe>
                </configuration>
            </plugin>
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link.
https://github.com/apache/incubator-datasketches-memory
 
- Include any stack-traces or any error messages
pom file clearly has `<includeProperty>git.commit.user.email</includeProperty>`

After running `mvn clean initialize` 

Resulting `git.properties` file has  `"git.commit.user.name" : "my name"

### Expected behavior
- Please provide a description of what you expected to happen.
It should output` git.commit.user.email`

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration) 3.0.0

- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk) 1.8.0_162

- the Maven-Version is being used (output of ``mvn --version``) 3.6.1

- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``) mac OSX 10.14.6

- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...) Terminal

- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
  mvn clean initialize

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment]
Thank you for reporting your problem here.

I'm honestly a bit baffled by this one and currently can not reproduce the issue.

I can only test on Linux and Windows system, but on there everything seems to work fine.

command run to test:
```bash
$ rm -rf target && mvn clean initialize | grep "BUILD SUCCESS" && grep "git.commit.user.email" ./target/git.properties
[INFO] BUILD SUCCESS
  "git.commit.user.email" : "xxxxxx@users.noreply.github.com",
```
works fine with
1) openjdk version "1.8.0_222"
```bash
$ mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/share/maven-3.6.1
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-55-generic", arch: "amd64", family: "unix"

$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

2) Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/share/maven-3.6.1
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk1.8.0_181/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-55-generic", arch: "amd64", family: "unix"
```

3) OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/share/maven-3.6.1
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-55-generic", arch: "amd64", family: "unix
```

4) Java(TM) SE Runtime Environment (build 1.8.0_181-b13) & Apache Maven 3.5.0 
```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/share/maven-3.5.0
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_181/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-55-generic", arch: "amd64", family: "unix"
```

I also honestly don't know what could cause this. 
Could you perhaps update your java and try again?
Maybe even try running the command in a docker container or cloud environment?

**Comment by leerho** [comment]
@TheSnoozer 

Thank you so much for your quick & detailed reply!!

Well now I'm baffled too. Because now it seems to be working!  I'm not sure what I did other than I made a few more commits of other stuff I'm working on.  After I got your comment, I tried again and voila! 

I have one more question, if I could beg your patience ...

Where does the `git.build.*` information come from? Are you pulling it from Maven?
Although I can see the convenience of including that info in the properties `build` information, building the project has nothing to do with `git`, per se.  I would think it might make more sense to label them `maven.build.*`.    Perhaps I am way off track here :)

BTW, This is one of the best documented maven plugins I have seen!  Great job!

**Comment by TheSnoozer** [comment]
> Well now I'm baffled too. Because now it seems to be working! I'm not sure what I did other than I made a few more commits of other stuff I'm working on. After I got your comment, I tried again and voila!

Awesome! Glad it is working! I can't tell what happened, but oh well it is working ;-)

> I have one more question, if I could beg your patience ...

Sure, anytime. Don't hesitate to ask ;-)

 
> Where does the `git.build.*` information come from? Are you pulling it from Maven?

The information is not being pulled from Maven. in short this plugin can operate in two different modes (configurable via `<useNativeGit>false</useNativeGit>`). One mode I would call the JGit
-mode and the other you can call native. For the Native mode this plugin asks the native git binary, for the jgit mode we use the [java git implementation from eclipse](https://www.eclipse.org/jgit/).

What populates the data can be found in the [GitDataProvider](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/ca97e60d810a782bad2354053029d5fd9e09d92d/src/main/java/pl/project13/maven/git/GitDataProvider.java#L122) which is more or less an abstract layer. The actual implementation of jgit lives in the [JGitProvider](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/ca97e60d810a782bad2354053029d5fd9e09d92d/src/main/java/pl/project13/maven/git/JGitProvider.java#L73) and the actual implementation of git lives in the [NativeGitProvider](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/ca97e60d810a782bad2354053029d5fd9e09d92d/src/main/java/pl/project13/maven/git/NativeGitProvider.java#L70).

To get the user-name the native git-implementation essentially runs `git config --get user.name`.
To easily add new properties the native git makes one call for each property (sounds costly, but in some extensive testing the native version appears to be much faster - see [my last benchmark](https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/408#issuecomment-487631736)). As you may notice this benchmark also has a section that highlights the runtime when you exclude/include properties. Essentially with version 3.0 I introduced the `maybePut` that only fetches the properties only when needed.

Please be aware that by using the native binary the plugin may break whenever the native binary behaves badly/differently. The official recommendation is that I would recommend to switch to the native version in case you observe any performance issue. I practice I would believe that you might be way better off using the native (never seen the git-binary behaving badly, just some weird issues calling processes under java that have gotten fixed already).

> Although I can see the convenience of including that info in the properties `build` information, building the project has nothing to do with `git`, per se. I would think it might make more sense to label them `maven.build.*`. Perhaps I am way off track here :)

Well yes and no. I would would say a bit tricky. I totally get your point, but I would argue that this is not a plugin developed by maven and hence the `maven.*` properties are not within our restriction. I'm not sure if we could get in trouble when we would do that, but I certainly would find it weird when some properties are generated with a different prefix (just FYI you could change your prefix entirely via `<prefix>git</prefix>` too). The safer version is just to have our own configurable prefix and let the user decide.

> BTW, This is one of the best documented maven plugins I have seen! Great job!

Thank you :-)

**Comment by TheSnoozer** [comment]
Feel free to open a new issue if you got any more question, but based on your response the 'issue' seems to be fixed ;-)
