### ISSUE TITLE
how to configration for show partial attributes in git.properties

### ISSUE THREAD

**Issue by looyo** [git-commit-id/maven-git-commit-id-plugin#434]
### Describe your idea
I only want to see commit-id、buildtime in git.properties
### Expected Behavior

I can configuration the plugin, set invisible  for some git attribute.

**Comment by TheSnoozer** [comment]
Based on the description please read https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/docs/using-the-plugin.md

When I understand it correctly you need:
```xml
<excludeProperties>
  <!-- <excludeProperty>git.user.*</excludeProperty> -->
</excludeProperties>
```
or 
```xml
<includeOnlyProperties>
  <!-- <includeOnlyProperty>^git.commit.id.full$</includeOnlyProperty> -->
</includeOnlyProperties>
```

Let me know if this helps.

**Comment by TheSnoozer** [comment]
assuming this has been answered.
