### ISSUE TITLE
Azure DevOps - Git branch name

### ISSUE THREAD

**Issue by dandragut** [git-commit-id/maven-git-commit-id-plugin#438]
### Describe your idea
AzureDevops checks out Git branches in detached mode, resulting in `git.branch` being populated with the commit hash.

### Expected Behavior
The branch name can be populated from `BUILD_SOURCEBRANCHNAME` environment vaiable as per [Azure Devops / Azure Pipelines - Build variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables)

### Additional context
Will provide a pull request soon with proposed changes for review.

**Comment by TheSnoozer** [comment]
Thanks for creating an issue! That sounds reasonable.

Just as a hint (if you not already know):
This sounds like it would be similar to the [TravisBuildServerData](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/build/TravisBuildServerData.java) or other BuildExtractors we already have for other CI environments. I guess in the easiest case you just need to write one for the Azure environment and [extend the functionality](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/build/BuildServerDataProvider.java#L90) to obtain such provider.

**Comment by dandragut** [comment]
Thanks @TheSnoozer 

I had a quick look around at the Azure Pipeline environment variables and the source code, I found exactly what you pointed out, thanks for that. Running some tests now and creating the pull request soon for you guys to review (Y)

**Comment by TheSnoozer** [comment]
Thanks for making the changes and improving this project!
Feel free to assign the MR to me and I'll review when I got some free time ;-)

**Comment by TheSnoozer** [comment]
Implemented via https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/439.

Thanks for your contribution!

**Comment by dandar3** [comment]
@TheSnoozer Entirely my please, thank you guys for writing the plugin in the first place! (Y)

**Comment by TheSnoozer** [comment]
It's always great to know that this plugin is still in use :-)
I personally have switched to gradle which has other downsides compared to maven ;-)

Anyhow, as far as i remember travis deploys snapshots of the master-branch to oss-sonatype. if you want to start to use this feature you could already do so, by specifying the Sonatype-Snapshot repo.

e.g.
```xml
<pluginRepositories>
    <pluginRepository>
        <id>sonatype-snapshots</id>
        <name>Sonatype Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

If you'd prefer a more official release feel free to ping me in https://github.com/git-commit-id/maven-git-commit-id-plugin/issues/432. Releases only happen randomly or when users (YOU) ask for it ;-)

**Comment by dandar3** [comment]
Thank you, didn't know about the Sonatype snapshot builds, I had deployed mine on our Artficatory to be able to test it. Thanks for the notes, whenever you feel it's worth releasing it it's fine, no pressure :-)
