### ISSUE TITLE
Mojo fails on remote repository urls of form:  url = https://:@git.server.com/pathToRepo.git

### ISSUE THREAD

**Issue by wnreynoldsWork** [git-commit-id/maven-git-commit-id-plugin#459]
### Describe the bug
Please provide a brief summary of the issue and provide a summarised description in the title above.

Gitlab urls with kerberos authentication have the format:

https://:@git.server.com/pathToRepo.git

See https://gitlab.com/gitlab-org/gitlab/merge_requests/70.

This type of url causes the plugin to fail with the error:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at pl.project13.core.GitDataProvider.stripCredentialsFromOriginUrl(GitDataProvider.java:318)

due to the code assuming there is a user name in the url. The workaround is to temporarily modify the url in .git/config to be a format that the plugin can understand

url = https://git.server.com/pathToRepo.git

and then revert it back to the correct url when pushing/pulling.

### Steps to Reproduce
- Please include the **full** configuration of the plugin

create a git repo, change the url = https://@:git.server.com in .git/config, run the plugin. You will crash with error above.

`            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.0.0</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <useNativeGit>true</useNativeGit>
                    <dotGitDirectory>../.git</dotGitDirectory>
                    <prefix>git</prefix>
                    <verbose>false</verbose>
                    <offline>true</offline>
                    <skip>false</skip>
                    <generateGitPropertiesFile>false</generateGitPropertiesFile>
                    <!-- generateGitPropertiesFilename>
                    ${project.build.outputDirectory}/git.properties
`

**Comment by TheSnoozer** [comment]
Fixed by https://github.com/git-commit-id/maven-git-commit-id-plugin/pull/460,

Thanks again for your report.

PS:
This should be usable by referring to the latest snapshot-version:
```
<pluginRepositories>
    <pluginRepository>
        <id>sonatype-snapshots</id>
        <name>Sonatype Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

**Comment by wnreynoldsWork** [comment]
thanks!
